# Config format schema number
format_version: 4

# Add Turns info to another channel
turns_channel: 1

###################
## Model options
model_params:
  model_architecture: "resnet50"

  history_num_frames: 1
  future_num_frames: 12  # 1 12
  step_time: 0.1
  render_ego_history: True
  load_pretrained: False

  history_num_frames_agents: 1
  history_num_frames_ego: 1

###################
## Input raster parameters
raster_params:
  # raster image size [pixels]
  raster_size:
    - 112
    - 112
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.5
    - 0.5
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.25
    - 0.5
  map_type: "py_semantic"

  # the keys are relative to the dataset environment variable
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.5

  # whether to completely disable traffic light faces in the semantic rasterizer
  disable_traffic_light_faces: False

  # When set to True, the rasterizer will set the raster origin at bottom left,
  # i.e. vehicles are driving on the right side of the road.
  # With this change, the vertical flipping on the raster used in the visualization code is no longer needed.
  # Set it to False for models trained before v1.1.0-25-g3c517f0 (December 2020).
  # In that case visualisation will be flipped (we've removed the flip there) but the model's input will be correct.
  set_origin_to_bottom: True

###################
## VectorNet Params
data_generation_params:
  # maximum number of other agents to take (if less will be padded)
  other_agents_num: 30  # 30 15
  # maximum distance from AoI for another agent to be picked
  max_agents_distance: 35
  # Parameters defining which and how many lanes to be retrieved
  lane_params:
    # maximum number of lanes to take into account
    # if less they will be padded; if more the closest to AoI are picked
    max_num_lanes: 30
    # max number of points per lane
    max_points_per_lane: 20
    # max number of points per crosswalk
    max_points_per_crosswalk: 20
    # maximum radius around the AoI for which we retrieve
    max_retrieval_distance_m: 35
    # max number of crosswalks
    max_num_crosswalks: 20

###################
## Data loader options
train_data_loader:
  key: "scenes/validate.zarr"  # "scenes/sample.zarr"
  # batch_size: 64  # Use the same batch size of RL rollout buffer
  shuffle: True
  num_workers: 4  # 4 16
  perturbation: True

val_data_loader:
  key: "scenes/sample.zarr"  # "scenes/sample.zarr"
  perturbation: False

scale_data_loader:
  key: "scenes/validate.zarr"  # "scenes/sample.zarr"
  # batch_size: 64  # Use the same batch size of RL rollout buffer
  shuffle: True
  perturbation: True

###################
## Gym params
gym_params:
  max_scene_id: 1000  # 40 1000
  max_val_scene_id: 100  # 40 100
  randomize_start_frame: True  # False
  overfit: False  # 强制限定一个场景id 过拟合  True
  overfit_id: 39  # 路口弯道
